# Generated by Django 6.0.3 on 2026-04-11 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employee_avatars/')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('id_card_number', models.CharField(blank=True, max_length=30, verbose_name='Số căn cước')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address_village', models.CharField(blank=True, max_length=255, verbose_name='Thôn/Xóm')),
                ('address_commune', models.CharField(blank=True, max_length=255, verbose_name='Xã/Phường')),
                ('address_district', models.CharField(blank=True, max_length=255, verbose_name='Quận/Huyện')),
                ('address_province', models.CharField(blank=True, max_length=255, verbose_name='Tỉnh/Thành phố')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, verbose_name='Tên chủ TK')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Tên ngân hàng')),
                ('date_joined_company', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('date_contract_signed', models.DateField(blank=True, null=True, verbose_name='Ngày ký HĐ chính thức')),
                ('contract_status', models.CharField(blank=True, choices=[('PROBATION', 'Thử việc'), ('FIXED_TERM', 'HĐ xác định thời hạn'), ('INDEFINITE', 'HĐ không xác định thời hạn')], default='PROBATION', max_length=20, verbose_name='Trạng thái hợp đồng')),
                ('work_status', models.CharField(choices=[('ACTIVE', 'Đang làm việc'), ('ON_LEAVE', 'Tạm nghỉ'), ('RESIGNED', 'Đã nghỉ')], default='ACTIVE', max_length=20, verbose_name='Trạng thái làm việc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_user', models.ForeignKey(blank=True, help_text='User duyệt yêu cầu cập nhật thông tin nhân viên', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('editor_user', models.ForeignKey(blank=True, help_text='User được phép chỉnh sửa thông tin tất cả nhân viên', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cấu hình quản lý nhân viên',
                'verbose_name_plural': 'Cấu hình quản lý nhân viên',
                'db_table': 'employee_config',
            },
        ),
        migrations.CreateModel(
            name='EmployeeUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(help_text='JSON dict of field_name: new_value', verbose_name='Dữ liệu thay đổi')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True, verbose_name='Ghi chú duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='employees.employee')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_update_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employee_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_update_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['work_status'], name='employees_work_st_74b72f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['contract_status'], name='employees_contrac_433bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeupdaterequest',
            index=models.Index(fields=['status'], name='employee_up_status_4b99e8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeupdaterequest',
            index=models.Index(fields=['employee', 'status'], name='employee_up_employe_534115_idx'),
        ),
    ]
