# Generated by Django 6.0.3 on 2026-04-11 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeconfig',
            name='approver_user',
        ),
        migrations.RemoveField(
            model_name='employeeconfig',
            name='editor_user',
        ),
        migrations.AddField(
            model_name='employeeconfig',
            name='approver_users',
            field=models.ManyToManyField(blank=True, help_text='Users duyệt yêu cầu cập nhật thông tin nhân viên', related_name='employee_approver_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeconfig',
            name='editor_users',
            field=models.ManyToManyField(blank=True, help_text='Users được phép chỉnh sửa thông tin tất cả nhân viên', related_name='employee_editor_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
