# Generated by Django 6.0.3 on 2026-04-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeeconfig_approver_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeupdaterequest',
            name='avatar_upload',
            field=models.ImageField(blank=True, help_text='Ảnh đại diện chờ duyệt (tạm thời)', null=True, upload_to='employee_update_avatars/', verbose_name='Ảnh đại diện tạm'),
        ),
    ]
