# Generated by Django 6.0.3 on 2026-04-12 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_description'),
        ('employees', '0003_employeeupdaterequest_avatar_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeconfig',
            name='reward_manager_users',
            field=models.ManyToManyField(blank=True, help_text='Users được phép quản lý khen thưởng nhân viên', related_name='employee_reward_manager_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Lý do khen thưởng')),
                ('reward_type', models.CharField(choices=[('CASH', 'Tiền mặt'), ('GIFT', 'Hiện vật')], default='CASH', max_length=10, verbose_name='Hình thức thưởng')),
                ('reward_detail', models.TextField(blank=True, verbose_name='Chi tiết thưởng')),
                ('reward_date', models.DateField(verbose_name='Thời gian khen thưởng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rewards', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='departments.department', verbose_name='Phòng khen thưởng')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'db_table': 'employee_rewards',
                'ordering': ['-reward_date', '-created_at'],
                'indexes': [models.Index(fields=['reward_date'], name='employee_re_reward__83ae66_idx'), models.Index(fields=['employee'], name='employee_re_employe_72170e_idx')],
            },
        ),
    ]
