# Generated by Django 6.0.3 on 2026-04-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeconfig_reward_manager_users_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='visible_on_dashboard',
            field=models.BooleanField(default=True, help_text='Nếu tắt, khen thưởng này sẽ không hiển thị ở mục Khen thưởng gần đây trên Dashboard.', verbose_name='Hiển thị trên Dashboard'),
        ),
    ]
