# Generated by Django 6.0.3 on 2026-04-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_reward_visible_on_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='employees.employee', verbose_name='Nhân viên'),
        ),
    ]
