# Generated by Django 6.0.3 on 2026-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_reward_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc HĐ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu HĐ'),
        ),
    ]
