# Generated by Django 6.0.3 on 2026-04-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_add_contract_start_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeconfig',
            name='force_profile_update',
            field=models.BooleanField(default=False, help_text='Nếu bật, người dùng phải cập nhật các trường trống được chỉ định trước khi truy cập hệ thống.', verbose_name='Bắt buộc cập nhật thông tin'),
        ),
        migrations.AddField(
            model_name='employeeconfig',
            name='required_fields',
            field=models.JSONField(blank=True, default=list, help_text="Danh sách field_name bắt buộc phải có dữ liệu. Ví dụ: ['phone','date_of_birth','avatar']", verbose_name='Trường bắt buộc'),
        ),
    ]
