# Generated by Django 6.0.3 on 2026-04-14 03:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_messagerecipient_is_important'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('font_family', models.CharField(default='inherit', max_length=100, verbose_name='Font chữ')),
                ('font_size', models.PositiveSmallIntegerField(default=14, verbose_name='Cỡ chữ (px)')),
                ('text_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Mã màu phải có dạng #RRGGBB', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Màu chữ')),
                ('bg_color', models.CharField(default='#1677ff', max_length=7, validators=[django.core.validators.RegexValidator(message='Mã màu phải có dạng #RRGGBB', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Màu nền')),
                ('speed', models.PositiveSmallIntegerField(default=20, help_text='Thời gian chạy hết 1 vòng', verbose_name='Tốc độ (giây)')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='messagerecipient',
            new_name='message_rec_user_id_8e0a65_idx',
            old_name='message_reci_user_id_5eca30_idx',
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
