# Generated by Django 6.0.3 on 2026-04-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_add_announcement_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('CONTACT', 'Thông tin liên hệ'), ('COPYRIGHT', 'Bản quyền'), ('SOCIAL', 'Mạng xã hội'), ('PARTNER', 'Đối tác'), ('CERTIFICATION', 'Chứng nhận')], max_length=20, verbose_name='Phân loại')),
                ('label', models.CharField(max_length=200, verbose_name='Nhãn')),
                ('value', models.TextField(blank=True, default='', verbose_name='Giá trị (URL/text)')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='Icon (tên Ant icon)')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Ảnh/Logo URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'footer_items',
                'ordering': ['section', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc hiển thị'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu hiển thị'),
        ),
    ]
