# Generated by Django 6.0.3 on 2026-04-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_permission_pages_and_uniq'),
        ('employees', '0007_add_contract_start_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_contract_status', models.CharField(choices=[('PROBATION', 'Thử việc'), ('FIXED_TERM', 'HĐ xác định thời hạn'), ('INDEFINITE', 'HĐ không xác định thời hạn')], default='FIXED_TERM', max_length=20, verbose_name='Trạng thái HĐ bắt đầu tính phép')),
                ('annual_leave_days', models.PositiveIntegerField(default=12, verbose_name='Số ngày phép tối đa/năm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình nghỉ phép',
                'verbose_name_plural': 'Cấu hình nghỉ phép',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('carried_over_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Ngày phép bảo lưu')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Ngày phép đã dùng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Số phép nhân viên',
                'verbose_name_plural': 'Số phép nhân viên',
                'ordering': ['-year'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
