# Generated by Django 6.0.3 on 2026-04-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_add_leave_config_balance'),
        ('employees', '0007_add_contract_start_end'),
        ('requestsystem', '0007_add_request_quick_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(verbose_name='Ngày nghỉ')),
                ('leave_type', models.CharField(choices=[('FULL_DAY', 'Nghỉ cả ngày'), ('MORNING', 'Nghỉ sáng'), ('AFTERNOON', 'Nghỉ chiều')], default='FULL_DAY', max_length=20, verbose_name='Loại nghỉ')),
                ('paid_type', models.CharField(choices=[('PAID', 'Nghỉ có lương'), ('UNPAID', 'Nghỉ không lương')], default='PAID', max_length=10, verbose_name='Nghỉ lương/không lương')),
                ('deducted_days', models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Số ngày trừ phép')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, verbose_name='Lý do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='requestsystem.request')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Bản ghi nghỉ phép',
                'verbose_name_plural': 'Bản ghi nghỉ phép',
                'ordering': ['-leave_date'],
            },
        ),
    ]
