# Generated by Django 6.0.3 on 2026-04-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_leaverequestrecord'),
        ('employees', '0007_add_contract_start_end'),
        ('requestsystem', '0007_add_request_quick_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffsiteWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Ngày làm việc ngoại viện')),
                ('work_type', models.CharField(choices=[('FULL_DAY', 'Cả ngày'), ('MORNING', 'Buổi sáng'), ('AFTERNOON', 'Buổi chiều')], default='FULL_DAY', max_length=20, verbose_name='Loại')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Địa điểm')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offsite_records', to='requestsystem.request')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offsite_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Bản ghi ngoại viện',
                'verbose_name_plural': 'Bản ghi ngoại viện',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_date', models.DateField(verbose_name='Ngày làm thêm')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('ot_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Số giờ làm thêm')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do làm thêm')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='requestsystem.request')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Bản ghi làm thêm',
                'verbose_name_plural': 'Bản ghi làm thêm',
                'ordering': ['-ot_date'],
            },
        ),
    ]
