# Generated by Django 6.0.3 on 2026-04-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_workflowstep_approver_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltemplate',
            name='type',
            field=models.CharField(db_index=True, help_text='Loại phê duyệt do người dùng tự đặt tên', max_length=100),
        ),
    ]
