# Generated by Django 6.0.3 on 2026-04-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_alter_approvaltemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltemplate',
            name='is_leave_request',
            field=models.BooleanField(default=False, help_text='Khi bật, tạo yêu cầu sẽ hiển thị form nghỉ phép và tự động trừ phép khi duyệt.', verbose_name='Liên kết với đơn xin nghỉ phép'),
        ),
    ]
