# Generated by Django 6.0.3 on 2026-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0008_approvaltemplate_is_leave_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltemplate',
            name='is_offsite_request',
            field=models.BooleanField(default=False, help_text='Khi bật, tạo yêu cầu sẽ hiển thị form đăng ký làm việc ngoại viện.', verbose_name='Liên kết với yêu cầu làm việc ngoại viện'),
        ),
        migrations.AddField(
            model_name='approvaltemplate',
            name='is_overtime_request',
            field=models.BooleanField(default=False, help_text='Khi bật, tạo yêu cầu sẽ hiển thị form đăng ký làm thêm.', verbose_name='Liên kết với đơn làm thêm'),
        ),
    ]
